version: '3.9'

services:
  flask-app:
    build: .
    ports:
      - "8080:5000"
    environment:
      DB_PORT: 5432
      DB_USER: postgres
      DB_HOST: database-1.cf6tpgryccx3.us-east-1.rds.amazonaws.com
      DB_NAME: postgres
      AWS_ACCESS_KEY_ID: AKIA37UMCVHJCJ253BGM
      AWS_SECRET_ACCESS_KEY: 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

